-- Exam Strategist: exams and exam_study_plans tables
-- Supports the elite academic strategist feature for exam prep

-- Exams table
CREATE TABLE exams (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  exam_date DATE NOT NULL,
  daily_hours DECIMAL(4,2) NOT NULL DEFAULT 3,
  materials_text TEXT,
  confidence_json JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Exam study plans (generated by strategist)
CREATE TABLE exam_study_plans (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  exam_id UUID NOT NULL REFERENCES exams(id) ON DELETE CASCADE,
  topic_analysis JSONB DEFAULT '[]'::jsonb,
  prioritization JSONB DEFAULT '[]'::jsonb,
  time_allocation JSONB DEFAULT '{}'::jsonb,
  sessions JSONB DEFAULT '[]'::jsonb,
  calendar JSONB DEFAULT '[]'::jsonb,
  insights JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(exam_id)
);

-- Indexes
CREATE INDEX idx_exams_user_id ON exams(user_id);
CREATE INDEX idx_exams_exam_date ON exams(exam_date);
CREATE INDEX idx_exams_created_at ON exams(created_at DESC);
CREATE INDEX idx_exam_study_plans_exam_id ON exam_study_plans(exam_id);

-- RLS
ALTER TABLE exams ENABLE ROW LEVEL SECURITY;
ALTER TABLE exam_study_plans ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own exams"
  ON exams FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own exams"
  ON exams FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own exams"
  ON exams FOR UPDATE
  USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own exams"
  ON exams FOR DELETE
  USING (auth.uid() = user_id);

CREATE POLICY "Users can view study plans of own exams"
  ON exam_study_plans FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM exams
      WHERE exams.id = exam_study_plans.exam_id
      AND exams.user_id = auth.uid()
    )
  );

CREATE POLICY "Users can insert study plans for own exams"
  ON exam_study_plans FOR INSERT
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM exams
      WHERE exams.id = exam_study_plans.exam_id
      AND exams.user_id = auth.uid()
    )
  );

CREATE POLICY "Users can update study plans of own exams"
  ON exam_study_plans FOR UPDATE
  USING (
    EXISTS (
      SELECT 1 FROM exams
      WHERE exams.id = exam_study_plans.exam_id
      AND exams.user_id = auth.uid()
    )
  );
